### PR TITLE
Add support for folders and trailing slashes in ignore when deploying

### PR DESCRIPTION
**Pull request by gausby**
I have to admit: I haven't tested this as much as I would, but it seems to work. I guess that we should add some unit tests for some of the helper functions soon (I will gladly do this at some point if time permits).

I had a problem, described in #32, where I noticed that hms does not ignore trailing slashes in `.gitignore`, so if I added `node_modules/`to my ignore file it would not get ignored during deploy. After looking into the issue I noticed that `compileIgnore` uses `path.basename` before comparing, effectually turning `/foo/bar` into `bar`.

Further more, the input to the module we use to create the compare patterns, minimatch, was not normalised in the same way. Which result in `node_modules/` would expect a trailing slash.

```js
var minimatch = require('minimatch')
var path = require('path')
console.log(minimatch.makeRe('node_modules/').test(path.basename('node_modules/'))) // false
```

To mitigate this I have tried to alter the functionality of `compileIgnore` to:

  * remove trailing slashes a pattern before adding it to the ignored patterns
  * remove trailing slashes from the input

```js
var minimatch = require('minimatch')
var path = require('path')
var normalizePath = function(_path) { return _path.split('/').filter(Boolean).join('/'); }
console.log(minimatch.makeRe(normalizePath('node_modules/')).test(normalizePath('node_modules/'))) // true
console.log(minimatch.makeRe(normalizePath('/foo/node_modules/')).test(normalizePath('/foo/node_modules'))) // true
console.log(minimatch.makeRe(normalizePath('/foo/node_modules/')).test(normalizePath('/bar/node_modules'))) // false
console.log(minimatch.makeRe(normalizePath('node_modules')).test(normalizePath('/foo/node_modules'))) // false
```

Note: we can not use `path.normalize`, as, while it does remove trailing slash from `path.normalize('/foo/bar/')` => `/foo/bar`, it does not remove slashes from `foo/` => `foo`. I guess this is to distinct between files and folders, which we might have to consider in hms as well.

That said, this could break a thing or two. I have to have some other eyes on this.

### CODE REVIEW

**Comment by gausby** [comment]
```js
console.log(minimatch.makeRe(normalizePath('node_modules')).test(normalizePath('/foo/node_modules')))
```
should actually return `true`

Gotta update this pull request.

**Comment by mafintosh** [comment]
Oh I though we where using [mafintosh/ignore-file](https://github.com/mafintosh/ignore-file). We should just use that.

**Comment by gausby** [comment]
Hah, why didn't that turn up in my searches? *face palming to the maximum extend*

**Comment by gausby** [comment]
Removed my changes. Replaced the implementation with the ignore-file project.

But it seems like `node_modules/` still doesn't ignore the node_modules-folder properly. Have to investigate, but the fix should be made to the ignore-file project at this point, I guess.

**Comment by gausby** [comment]
There. I've removed some changes and rebased the pull request to remove the dud commits. Now it only contain the change from using a homebrew gitignore implementation to use the mafintosh/ignore-file project, and dropped the dependency on minimatch.

As far as I can see the functionality is the same. Unless something is obviously wrong in this pull request I would like to propose that we merge it to master :)

**Comment by freeall** [comment]
Does this close #32?

**Comment by gausby** [comment]
Nope. But we should fix it elsewhere.

The issue changed scope before it was merged. I replaced the homebrew ignore code with an module, but this does not change the size of the generated tarball when deploying. #32 is still an issue.

**Pull request merged**
