### PR TITLE
Allow all commands to use the --key option.

### PR DESCRIPTION
**Pull request by sorribas**
With this, all the commands can use the --key option (before it could only be used with the `remotes` command). With this PR you can do stuff like this

`hms deploy root@example.com main-website --key /path/to/private/key`

### CODE REVIEW

**Comment by mafintosh** [comment]
is `var c = client(remote, {key: options.key})` not the same?

**Comment by sorribas** [comment]
Yeah, let me change that.

**Comment by sorribas** [comment]
@mafintosh fixed

**Comment by mafintosh** [comment]
3.3.0

**Pull request merged**
